# ATENCION: NO PONER CARACTERES QUE NO SEAN DEL 
# ALFABETO INGLES, NI SIQUIERA EN LOS COMENTARIOS.
spring.profiles.active=prod
spring.application.name=testspring
#server.servlet.context-path=/testspring
#spring.security.user.name=jag
spring.security.user.password=jag
#
# To save data log in a file:
logging.file.name=logs/csi.log
#
# To save session data in database
#spring.session.store-type=jdbc // A partir SpringBoot no hace falta
spring.session.jdbc.initialize-schema=always
server.servlet.session.timeout=30m
#

# Configuration for i18n message files path
spring.messages.basename=i18n/message
spring.messages.encoding=UTF-8
