create table Customer (age integer, totalPurchases float(53), id bigint generated by default as identity, cardNumber varchar(255), name varchar(255), primary key (id));
create table ROLES (ROLENAME varchar(50) not null, primary key (ROLENAME));
create table USERS (ENABLED boolean not null, EXPIRY_DATE_ACCOUNT date not null, EXPIRY_DATE_CREDENTIALS date not null, LOCKED_ACCOUNT boolean not null, ID bigint generated by default as identity, USERNAME varchar(50) not null unique, EMAIL varchar(100) not null unique, PASSWORD varchar(100) not null, fullname varchar(100) not null, primary key (ID));
create table USERS_HAS_ROLES (FK_USERS_ID bigint not null, FK_ROLES_ROLENAME varchar(255) not null, primary key (FK_USERS_ID, FK_ROLES_ROLENAME));
alter table if exists USERS_HAS_ROLES add constraint FKmweugxov8fndr7t6mc1w3c8kp foreign key (FK_ROLES_ROLENAME) references ROLES;
alter table if exists USERS_HAS_ROLES add constraint FKbhfbxpypewmujo22f4b7vor8d foreign key (FK_USERS_ID) references USERS;
