create table Customer (age integer not null, totalPurchases float(53) not null, id bigint not null auto_increment, cardNumber varchar(16), name varchar(50) not null, primary key (id)) engine=InnoDB;
create table Family (id bigint not null auto_increment, name CHAR(50) CHECK(LENGTH(NAME) >= 1) not null, primary key (id)) engine=InnoDB;
create table Product (discount float(53) not null, price float(53) not null, stock integer not null check (stock>=0), familyId bigint not null, id bigint not null auto_increment, valuationId bigint not null, name varchar(50) not null, URL varchar(250) not null, primary key (id)) engine=InnoDB;
create table ROLES (id bigint not null auto_increment, ROLENAME varchar(50) not null, primary key (id)) engine=InnoDB;
create table USERS (ENABLED bit not null, EXPIRY_DATE_ACCOUNT date not null, EXPIRY_DATE_CREDENTIALS date not null, LOCKED_ACCOUNT bit not null, ID bigint not null auto_increment, USERNAME varchar(50) not null, EMAIL varchar(100) not null, PASSWORD varchar(100) not null, fullname varchar(100) not null, primary key (ID)) engine=InnoDB;
create table USERS_HAS_ROLES (FK_ROLES_ID bigint not null, FK_USERS_ID bigint not null, primary key (FK_ROLES_ID, FK_USERS_ID)) engine=InnoDB;
create table Valuation (id bigint not null auto_increment, name varchar(50) not null, primary key (id)) engine=InnoDB;
alter table ROLES add constraint UKcjdiarbbt9mrtu439xfnnsgcq unique (ROLENAME);
alter table USERS add constraint UKh6k33r31i2nvrri9lok4r163j unique (USERNAME);
alter table USERS add constraint UK81nqioeq3njjrwqaltk2mcobj unique (EMAIL);
alter table Product add constraint FKo2739prt3726dwphva62dyi8n foreign key (familyId) references Family (id) on delete restrict;
alter table Product add constraint FKly89xto0enmi9251oul8waqam foreign key (valuationId) references Valuation (id) on delete restrict;
alter table USERS_HAS_ROLES add constraint FKkcxvycyxtf90u7vhpk7nwbk4l foreign key (FK_ROLES_ID) references ROLES (id);
alter table USERS_HAS_ROLES add constraint FKbhfbxpypewmujo22f4b7vor8d foreign key (FK_USERS_ID) references USERS (ID);
